# Generated by Django 5.1.1 on 2024-09-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=30)),
                ('laboratory', models.CharField(max_length=100)),
            ],
        ),
    ]
