# Generated by Django 5.1.1 on 2024-09-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='laboratory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='substance',
            field=models.TextField(max_length=255),
        ),
    ]
