version: '3.9'

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
  backup:
    image: postgres:13-alpine
    depends_on:
      - psql
    env_file:
      - ./dotenv_files/.env
    command: >
      sh -c 'pg_dump -h psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -F c -b -v -f /var/lib/postgresql/data/backup_da_base.dump'
    volumes:
      - ./backup:/var/lib/postgresql/data/
      - ./backups:/backups 